[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "st-experiment-template"
version = "0.1.0"
description = "DS experiment template."
readme = "README.md"
authors = [
    { name = "Samuel Thorpe", email = "sam@neursignal.com" }
]
requires-python = ">=3.10"

dependencies = [
    "gitpython",
    "dill",
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "plotly",
    "boto3",
    "psutil",
    "pyyaml",
    "requests",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "jupyter",
    "nbconvert",
]
test = [
    "pytest",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["st_experiment_template*"]

[tool.coverage.run]
source = ["st_experiment_template"]
branch = true

[tool.coverage.report]
omit = [
  "tests/*",
]

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E203"]